name: Build and Publish Docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker image tag
        id: vars
        run: |
          ref="$(echo -n "${GITHUB_REF#refs/*/}" | tr -c 'A-Za-z0-9._' -)"
          if [[ "$ref" == "main" ]] ; then ref=latest ; fi
          echo ::set-output "name=tag::$ref"

      - name: Build exporter
        id: exporter_docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vega-exporter:${{ steps.vars.outputs.tag }}

      - name: Exporter image digest
        run: echo ${{ steps.exporter_docker_build.outputs.digest }}

      - name: Build mainnet-observer
        id: observer_docker_build
        uses: docker/build-push-action@v3
        with:
          context: mainnet-observer
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mainnet-observer:${{ steps.vars.outputs.tag }}

      - name: Mainnet-observer image digest
        run: echo ${{ steps.observer_docker_build.outputs.digest }}
